# -*- coding: utf-8 -*-
"""Recipe_generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6Qj4LE7bllI9iRLD6_ToE1u9ZVuLspJ
"""

# ✅ Step 1: Install required libraries
!pip install transformers gradio -q

# ✅ Step 2: Import modules
from transformers import GPT2LMHeadModel, GPT2Tokenizer, pipeline
import gradio as gr

# ✅ Step 3: Load distilgpt2 (lightweight & fast)
model_name = "distilgpt2"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)

# ✅ Step 4: Text generation pipeline
generator = pipeline("text-generation", model=model, tokenizer=tokenizer)

# ✅ Step 5: Define the recipe generation logic
def generate_recipe(dish_name):
    prompt = f"Recipe: {dish_name}\nIngredients:\n"
    output = generator(prompt,
                       max_length=300,
                       temperature=0.8,
                       top_k=50,
                       top_p=0.95,
                       repetition_penalty=1.2,
                       num_return_sequences=1)
    return output[0]["generated_text"]

# ✅ Step 6: Gradio Interface
gr.Interface(
    fn=generate_recipe,
    inputs=gr.Textbox(label="Enter Dish Name (e.g. Chicken Biryani)"),
    outputs=gr.Textbox(label="Generated Recipe"),
    title="🔥 Efficient GenAI Recipe Generator (distilGPT2)",
    description="Fast and realistic recipe generator using distilled GPT2. Enter a dish name and get ingredients + steps instantly.",
).launch()